CC = clang
CFLAGS = 

all: da client

lib.o: lib.c lib.h
	$(CC) -c $(CFLAGS) lib.c -o lib.o

da: daemon.c
	$(CC) $(CFLAGS) -o da daemon.c

client: full_client.c lib.o
	$(CC) $(CFLAGS) -o client full_client.c lib.o

clean:
	rm -f *.o da client
